# Integer stat columns (used for SUM totals and zero-fill)
STAT_COLS = ["PTS", "FGM", "FGA", "FG3M", "FG3A", "FTM", "FTA", "OREB", "DREB", "REB", "AST", "TO", "STL", "BLK"]

# Percentage columns are calculated — excluded from integer casting and SUM totals
PCT_COLS = ["FG_PCT", "FG3_PCT", "FT_PCT"]

OUTPUT_COLS = [
    "Fantasy_Owner", "PLAYER_ID", "PLAYER", "TEAM", "MATCHUP",
    "PTS",
    "FGM", "FGA", "FG_PCT",
    "FG3M", "FG3A", "FG3_PCT",
    "FTM", "FTA", "FT_PCT",
    "OREB", "DREB", "REB",
    "AST", "TO", "STL", "BLK",
]

OWNER_COLORS = {
    "Aaron":   "DDEEFF",
    "Brian":   "D5F5E3",
    "Michael": "FFF9C4",
    "Mitch":   "FCE4EC",
    "Reed":    "EDE7F6",
    "Russ":    "FFF3E0",
    "Tim":     "E0F7FA",
}

ROSTER = [
    {"Fantasy_Owner": "Aaron",   "PLAYER": "Aaron Gordon",            "PLAYER_ID": 203932},
    {"Fantasy_Owner": "Aaron",   "PLAYER": "Brandon Miller",          "PLAYER_ID": 1641706},
    {"Fantasy_Owner": "Aaron",   "PLAYER": "Cade Cunningham",         "PLAYER_ID": 1630595},
    {"Fantasy_Owner": "Aaron",   "PLAYER": "Deni Avdija",             "PLAYER_ID": 1630166},
    {"Fantasy_Owner": "Aaron",   "PLAYER": "Donovan Clingan",         "PLAYER_ID": 1642270},
    {"Fantasy_Owner": "Aaron",   "PLAYER": "Isaiah Hartenstein",      "PLAYER_ID": 1628392},
    {"Fantasy_Owner": "Aaron",   "PLAYER": "Isaiah Stewart",          "PLAYER_ID": 1630191},
    {"Fantasy_Owner": "Aaron",   "PLAYER": "Jakob Poeltl",            "PLAYER_ID": 1627751},
    {"Fantasy_Owner": "Aaron",   "PLAYER": "Jalen Williams",          "PLAYER_ID": 1631114},
    {"Fantasy_Owner": "Aaron",   "PLAYER": "Julius Randle",           "PLAYER_ID": 203944},
    {"Fantasy_Owner": "Aaron",   "PLAYER": "Reed Sheppard",           "PLAYER_ID": 1642263},
    {"Fantasy_Owner": "Aaron",   "PLAYER": "Stephon Castle",          "PLAYER_ID": 1642264},
    {"Fantasy_Owner": "Brian",   "PLAYER": "Amen Thompson",           "PLAYER_ID": 1641708},
    {"Fantasy_Owner": "Brian",   "PLAYER": "Ausar Thompson",          "PLAYER_ID": 1641709},
    {"Fantasy_Owner": "Brian",   "PLAYER": "Cason Wallace",           "PLAYER_ID": 1641717},
    {"Fantasy_Owner": "Brian",   "PLAYER": "Desmond Bane",            "PLAYER_ID": 1630217},
    {"Fantasy_Owner": "Brian",   "PLAYER": "Devin Vassell",           "PLAYER_ID": 1630170},
    {"Fantasy_Owner": "Brian",   "PLAYER": "Donte DiVincenzo",        "PLAYER_ID": 1628978},
    {"Fantasy_Owner": "Brian",   "PLAYER": "Jalen Suggs",             "PLAYER_ID": 1630591},
    {"Fantasy_Owner": "Brian",   "PLAYER": "Jamal Murray",            "PLAYER_ID": 1627750},
    {"Fantasy_Owner": "Brian",   "PLAYER": "Julian Champagnie",       "PLAYER_ID": 1630577},
    {"Fantasy_Owner": "Brian",   "PLAYER": "Karl-Anthony Towns",      "PLAYER_ID": 1626157},
    {"Fantasy_Owner": "Brian",   "PLAYER": "Kelly Oubre Jr.",         "PLAYER_ID": 1626162},
    {"Fantasy_Owner": "Brian",   "PLAYER": "Shai Gilgeous-Alexander", "PLAYER_ID": 1628983},
    {"Fantasy_Owner": "Michael", "PLAYER": "Ajay Mitchell",           "PLAYER_ID": 1642349},
    {"Fantasy_Owner": "Michael", "PLAYER": "Brandon Ingram",          "PLAYER_ID": 1627742},
    {"Fantasy_Owner": "Michael", "PLAYER": "De'Aaron Fox",            "PLAYER_ID": 1628368},
    {"Fantasy_Owner": "Michael", "PLAYER": "Devin Booker",            "PLAYER_ID": 1626164},
    {"Fantasy_Owner": "Michael", "PLAYER": "Evan Mobley",             "PLAYER_ID": 1630596},
    {"Fantasy_Owner": "Michael", "PLAYER": "Jayson Tatum",            "PLAYER_ID": 1628369},
    {"Fantasy_Owner": "Michael", "PLAYER": "Kon Knueppel",            "PLAYER_ID": 1642851},
    {"Fantasy_Owner": "Michael", "PLAYER": "LaMelo Ball", "PLAYER_ID": 1630163},
    {"Fantasy_Owner": "Michael", "PLAYER": "Moussa Diabaté",          "PLAYER_ID": 1631217},
    {"Fantasy_Owner": "Michael", "PLAYER": "Naz Reid",                "PLAYER_ID": 1629675},
    {"Fantasy_Owner": "Michael", "PLAYER": "Onyeka Okongwu",          "PLAYER_ID": 1630168},
    {"Fantasy_Owner": "Michael", "PLAYER": "Payton Pritchard",        "PLAYER_ID": 1630202},
    {"Fantasy_Owner": "Mitch",   "PLAYER": "Alperen Sengun",          "PLAYER_ID": 1630578},
    {"Fantasy_Owner": "Mitch",   "PLAYER": "Christian Braun",         "PLAYER_ID": 1631128},
    {"Fantasy_Owner": "Mitch",   "PLAYER": "Derrick White",           "PLAYER_ID": 1628401},
    {"Fantasy_Owner": "Mitch",   "PLAYER": "Duncan Robinson",         "PLAYER_ID": 1629130},
    {"Fantasy_Owner": "Mitch",   "PLAYER": "Jabari Smith Jr.",        "PLAYER_ID": 1631095},
    {"Fantasy_Owner": "Mitch",   "PLAYER": "Jaden McDaniels",         "PLAYER_ID": 1630183},
    {"Fantasy_Owner": "Mitch",   "PLAYER": "Jalen Duren",             "PLAYER_ID": 1631105},
    {"Fantasy_Owner": "Mitch",   "PLAYER": "Jalen Johnson",           "PLAYER_ID": 1630552},
    {"Fantasy_Owner": "Mitch",   "PLAYER": "Josh Hart",               "PLAYER_ID": 1628404},
    {"Fantasy_Owner": "Mitch",   "PLAYER": "Nickeil Alexander-Walker","PLAYER_ID": 1629638},
    {"Fantasy_Owner": "Mitch",   "PLAYER": "Peyton Watson",           "PLAYER_ID": 1631212},
    {"Fantasy_Owner": "Mitch",   "PLAYER": "Tari Eason",              "PLAYER_ID": 1631106},
    {"Fantasy_Owner": "Reed",    "PLAYER": "Bam Adebayo",             "PLAYER_ID": 1628389},
    {"Fantasy_Owner": "Reed",    "PLAYER": "Chet Holmgren",           "PLAYER_ID": 1631096},
    {"Fantasy_Owner": "Reed",    "PLAYER": "James Harden",            "PLAYER_ID": 201935},
    {"Fantasy_Owner": "Reed",    "PLAYER": "Jaylen Brown",            "PLAYER_ID": 1627759},
    {"Fantasy_Owner": "Reed",    "PLAYER": "Kawhi Leonard",           "PLAYER_ID": 202695},
    {"Fantasy_Owner": "Reed",    "PLAYER": "Kevin Durant",            "PLAYER_ID": 201142},
    {"Fantasy_Owner": "Reed",    "PLAYER": "Luka Dončić",             "PLAYER_ID": 1629029},
    {"Fantasy_Owner": "Reed",    "PLAYER": "Neemias Queta",           "PLAYER_ID": 1629674},
    {"Fantasy_Owner": "Reed",    "PLAYER": "Paul George",             "PLAYER_ID": 202331},
    {"Fantasy_Owner": "Reed",    "PLAYER": "Rudy Gobert",             "PLAYER_ID": 203497},
    {"Fantasy_Owner": "Reed",    "PLAYER": "Stephen Curry",           "PLAYER_ID": 201939},
    {"Fantasy_Owner": "Reed",    "PLAYER": "VJ Edgecombe",            "PLAYER_ID": 1642845},
    {"Fantasy_Owner": "Russ",    "PLAYER": "Anthony Edwards",         "PLAYER_ID": 1630162},
    {"Fantasy_Owner": "Russ",    "PLAYER": "Cameron Johnson",         "PLAYER_ID": 1629661},
    {"Fantasy_Owner": "Russ",    "PLAYER": "Darius Garland",          "PLAYER_ID": 1629636},
    {"Fantasy_Owner": "Russ",    "PLAYER": "Donovan Mitchell",        "PLAYER_ID": 1628378},
    {"Fantasy_Owner": "Russ",    "PLAYER": "Dyson Daniels",           "PLAYER_ID": 1630700},
    {"Fantasy_Owner": "Russ",    "PLAYER": "Immanuel Quickley",       "PLAYER_ID": 1630193},
    {"Fantasy_Owner": "Russ",    "PLAYER": "LeBron James",            "PLAYER_ID": 2544},
    {"Fantasy_Owner": "Russ",    "PLAYER": "Mikal Bridges",           "PLAYER_ID": 1628969},
    {"Fantasy_Owner": "Russ",    "PLAYER": "Nikola Jokić",            "PLAYER_ID": 203999},
    {"Fantasy_Owner": "Russ",    "PLAYER": "Nikola Vučević",          "PLAYER_ID": 202696},
    {"Fantasy_Owner": "Russ",    "PLAYER": "Paolo Banchero",          "PLAYER_ID": 1631094},
    {"Fantasy_Owner": "Russ",    "PLAYER": "Tobias Harris",           "PLAYER_ID": 202699},
    {"Fantasy_Owner": "Tim",     "PLAYER": "CJ McCollum",             "PLAYER_ID": 203468},
    {"Fantasy_Owner": "Tim",     "PLAYER": "Daniss Jenkins",          "PLAYER_ID": 1642450},
    {"Fantasy_Owner": "Tim",     "PLAYER": "Dylan Harper",            "PLAYER_ID": 1642844},
    {"Fantasy_Owner": "Tim",     "PLAYER": "Jalen Brunson",           "PLAYER_ID": 1628973},
    {"Fantasy_Owner": "Tim",     "PLAYER": "Jarrett Allen",           "PLAYER_ID": 1628386},
    {"Fantasy_Owner": "Tim",     "PLAYER": "Keldon Johnson",          "PLAYER_ID": 1629640},
    {"Fantasy_Owner": "Tim",     "PLAYER": "Miles Bridges",           "PLAYER_ID": 1628970},
    {"Fantasy_Owner": "Tim",     "PLAYER": "OG Anunoby",              "PLAYER_ID": 1628384},
    {"Fantasy_Owner": "Tim",     "PLAYER": "RJ Barrett",              "PLAYER_ID": 1629628},
    {"Fantasy_Owner": "Tim",     "PLAYER": "Scottie Barnes",          "PLAYER_ID": 1630567},
    {"Fantasy_Owner": "Tim",     "PLAYER": "Tyrese Maxey",            "PLAYER_ID": 1630178},
    {"Fantasy_Owner": "Tim",     "PLAYER": "Victor Wembanyama",       "PLAYER_ID": 1641705},
]
